In [2]:
# import cell
import pandas as pd
import numpy as np

data14 = pd.read_csv("property-assessment-fy2014.csv")

data15 = pd.read_csv("property-assessment-fy2015.csv")

data16 = pd.read_csv("property-assessment-fy2016.csv")
#data16 = data16[['PID', 'R_HEAT_TYP']]


data17 = pd.read_csv("property-assessment-fy2017.csv")
#data17 = data17[['PID', 'R_HEAT_TYP']]


data18 = pd.read_csv("ast2018full.csv")
#data18 = data18[['PID', 'R_HEAT_TYP']]

C:\Users\cindy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (15,46,53,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\cindy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (60,63) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\cindy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (15,60,63) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
data18.columns

Index(['PID', 'CM_ID', 'GIS_ID', 'ST_NUM', 'ST_NAME', 'ST_NAME_SUF',
       'UNIT_NUM', 'ZIPCODE', 'PTYPE', 'LU', 'OWN_OCC', 'OWNER',
       'MAIL_ADDRESSEE', 'MAIL_ADDRESS', 'MAIL CS', 'MAIL_ZIPCODE', 'AV_LAND',
       'AV_BLDG', 'AV_TOTAL', 'GROSS_TAX', 'LAND_SF', 'YR_BUILT', 'YR_REMOD',
       'GROSS_AREA', 'LIVING_AREA', 'NUM_FLOORS', 'STRUCTURE_CLASS',
       'R_BLDG_STYL', 'R_ROOF_TYP', 'R_EXT_FIN', 'R_TOTAL_RMS', 'R_BDRMS',
       'R_FULL_BTH', 'R_HALF_BTH', 'R_BTH_STYLE', 'R_BTH_STYLE2',
       'R_BTH_STYLE3', 'R_KITCH', 'R_KITCH_STYLE', 'R_KITCH_STYLE2',
       'R_KITCH_STYLE3', 'R_HEAT_TYP', 'R_AC', 'R_FPLACE', 'R_EXT_CND',
       'R_OVRALL_CND', 'R_INT_CND', 'R_INT_FIN', 'R_VIEW', 'S_NUM_BLDG',
       'S_BLDG_STYL', 'S_UNIT_RES', 'S_UNIT_COM', 'S_UNIT_RC', 'S_EXT_FIN',
       'S_EXT_CND', 'U_BASE_FLOOR', 'U_NUM_PARK', 'U_CORNER', 'U_ORIENT',
       'U_TOT_RMS', 'U_BDRMS', 'U_FULL_BTH', 'U_HALF_BTH', 'U_BTH_STYLE',
       'U_BTH_STYLE2', 'U_BTH_STYLE3', 'U_KITCH_TYPE', 'U_KITCH_STYLE',
       'U_HEAT_TYP', 'U_AC', 'U_FPLACE', 'U_INT_FIN', 'U_INT_CND', 'U_VIEW'],
      dtype='object')

In [169]:
#selecting only interested column
train14 = data14[['Parcel_ID', 'ZIPCODE', 'R_HEAT_TYP', 'LU', 'AV_TOTAL',
                 "YR_BUILT", "STRUCTURE_CLASS","R_AC",
                 "U_AC", "U_HEAT_TYP", "OWN_OCC", "LIVING_AREA"]]
train15 = data15[['PID', 'ZIPCODE', 'R_HEAT_TYP', 'LU', 'AV_TOTAL',
                 "YR_BUILT", "STRUCTURE_CLASS","R_AC",
                 "U_AC", "U_HEAT_TYP", "OWN_OCC", "LIVING_AREA"]]
train16 = data16[['PID', 'ZIPCODE', 'R_HEAT_TYP', 'LU', 'AV_TOTAL',
                 "YR_BUILT", "STRUCTURE_CLASS","R_AC",
                 "U_AC", "U_HEAT_TYP", "OWN_OCC", "LIVING_AREA"]]
train17 = data17[['PID', 'ZIPCODE', 'R_HEAT_TYP', 'LU', 'AV_TOTAL',
                 "YR_BUILT", "STRUCTURE_CLASS","R_AC",
                 "U_AC", "U_HEAT_TYP", "OWN_OCC", "LIVING_AREA"]]
train18 = data18[['PID', 'ZIPCODE', 'R_HEAT_TYP', 'LU', 'AV_TOTAL',
                 "YR_BUILT", "STRUCTURE_CLASS","R_AC",
                 "U_AC", "U_HEAT_TYP", "OWN_OCC", "LIVING_AREA"]]

In [170]:
train14.head(10)
# First, by looking at data, I found R_HEAT_TYP and U_HEAT_TYP don't coexist.
# the dependent variable of our final model is Heat type

#drop rows when R_HEAT_TYP and U_HEAT_TYP are both NAN
train14 = train14.dropna(subset=["R_HEAT_TYP", "U_HEAT_TYP"], how='all')
train15 = train15.dropna(subset=["R_HEAT_TYP", "U_HEAT_TYP"], how='all')
train16 = train16.dropna(subset=["R_HEAT_TYP", "U_HEAT_TYP"], how='all')
train17 = train17.dropna(subset=["R_HEAT_TYP", "U_HEAT_TYP"], how='all')
train18 = train18.dropna(subset=["R_HEAT_TYP", "U_HEAT_TYP"], how='all')

In [171]:
train14.head(15)
# since we want to do a regression model, we have to delete rows where AV_TOTAL is zero
# AV_TOTAL: Total assessed value for property
train14 = train14[(train14.AV_TOTAL != 0)]
train15 = train15[(train15.AV_TOTAL != 0)]
train16 = train16[(train16.AV_TOTAL != 0)]
train17 = train17[(train17.AV_TOTAL != 0)]
train18 = train18[(train18.AV_TOTAL != 0)]

In [234]:
train14.ZIPCODE = train14.ZIPCODE.str.rstrip('_')
train15.ZIPCODE = train15.ZIPCODE.str.rstrip('_')
train16.ZIPCODE = train16.ZIPCODE.str.rstrip('_')
train17.ZIPCODE = train17.ZIPCODE.str.rstrip('_')
train18.ZIPCODE = train18.ZIPCODE.astype(int).astype(str).str.zfill(5)

#deal with zipcode

In [236]:
train18.head(25)

,PID,ZIPCODE,R_HEAT_TYP,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,R_AC,U_AC,U_HEAT_TYP,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP
0,100001000,02128,W,R3,483100,1900.0,R,N,NaN,NaN,Y,2202.0,R,N,W
1,100002000,02128,F,R3,532100,1920.0,R,C,NaN,NaN,N,2307.0,R,C,F
2,100003000,02128,S,R3,484300,1905.0,R,N,NaN,NaN,N,2268.0,R,N,S
3,100004000,02128,W,R3,462700,1900.0,R,N,NaN,NaN,N,2028.0,R,N,W
4,100005000,02128,W,R2,471900,1900.0,R,N,NaN,NaN,Y,2546.0,R,N,W
5,100006000,02128,E,R3,568200,1900.0,R,N,NaN,NaN,Y,4362.0,R,N,E
6,100007000,02128,W,R3,611500,1900.0,R,N,NaN,NaN,N,4296.0,R,N,W
7,100008000,02128,W,R3,628200,1900.0,R,N,NaN,NaN,Y,4080.0,R,N,W
8,100009000,02128,W,R3,524200,1900.0,R,N,NaN,NaN,Y,2937.0,R,N,W
9,100010000,02128,W,R3,302000,1900.0,R,N,NaN,NaN,Y,3241.0,R,N,W
10,100011000,02128,F,R2,562300,1900.0,R,C,NaN,NaN,Y,3402.0,R,C,F
11,100012000,02128,W,R3,525700,1900.0,R,N,NaN,NaN,Y,3193.0,R,N,W
12,100013000,02128,W,R3,565000,1900.0,R,N,NaN,NaN,N,3033.0,R,N,W
13,100014000,02128,W,R3,591100,1900.0,R,N,NaN,NaN,Y,3642.0,R,N,W
14,100015000,02128,W,R2,502000,1900.0,R,N,NaN,NaN,Y,2332.0,R,N,W
15,100016000,02128,W,R2,492200,1899.0,R,N,NaN,NaN,Y,3057.0,R,N,W
16,100017000,02128,W,R3,426800,1900.0,R,N,NaN,NaN,N,2883.0,R,N,W
17,100018000,02128,W,R3,571500,1900.0,R,N,NaN,NaN,N,4336.0,R,N,W
18,100019000,02128,W,R3,624600,1900.0,R,N,NaN,NaN,N,4316.0,R,N,W
19,100020000,02128,W,R3,586900,1900.0,R,N,NaN,NaN,Y,3807.0,R,N,W
20,100021000,02128,W,R1,213200,1910.0,R,N,NaN,NaN,Y,1122.0,R,N,W
21,100022000,02128,W,R3,544100,1900.0,R,N,NaN,NaN,Y,3405.0,R,N,W
22,100023000,02128,E,R3,536400,1900.0,R,N,NaN,NaN,Y,2580.0,R,N,E
23,100024000,02128,W,R3,505600,1900.0,R,N,NaN,NaN,N,3084.0,R,N,W
24,100025000,02128,W,R3,534300,1910.0,R,N,NaN,NaN,N,3327.0,R,N,W

In [237]:
pd.isnull(train14.loc[2]["U_AC"])

True

In [238]:
listtrain = [train14, train15, train16, train17, train18]
dflist = []
for i in range(len(listtrain)):
    a = listtrain[i]
    #a = a.fillna("N/A")
    a.RorU = "R"
    a.AC = "C"
    a.HEAT_TYP = ""
    for i, row in a.iterrows():  
        RorU_val = "U"
        AC_val = "N"
        HEAT_TYP_val = "N"
    
        if pd.isnull(a.loc[i]['R_AC']) == False:
            RorU_val = "R"
            AC_val = a.loc[i]["R_AC"]
            HEAT_TYP_val = a.loc[i]["R_HEAT_TYP"]
        else:
            RorU_val = "U"
            AC_val = a.loc[i]["U_AC"]
            HEAT_TYP_val = a.loc[i]["U_HEAT_TYP"]
        
        a.set_value(i, "RorU", RorU_val)
        a.set_value(i, "AC", AC_val)
        a.set_value(i, "HEAT_TYP", HEAT_TYP_val)

    a = a.drop(['R_AC', 'U_AC', 'R_HEAT_TYP', 'U_HEAT_TYP'], axis=1)
    dflist.append(a)

C:\Users\cindy\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\cindy\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
C:\Users\cindy\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [239]:
# traindata together in a list
dflist[0]
dflist[0].columns = ['PID' if x=='Parcel_ID' else x for x in dflist[0].columns]
dflist[0].head(20)

,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP
2,2205668000_,02135,R3,604700,1920,R,N,2834.0,R,N,W
5,2205665004_,02135,CD,335400,1920,NaN,N,1401.0,U,N,W
6,2205665002_,02135,CD,357300,1920,NaN,N,1410.0,U,N,W
8,2205664000_,02135,R2,567000,1920,R,Y,2952.0,R,N,F
9,2205663001_,02135,R1,477600,1920,R,Y,2390.0,R,N,W
10,2205663000_,02135,R1,442700,1920,R,Y,2347.0,R,N,W
11,2205662020_,02135,R2,549000,1910,R,Y,2545.0,R,N,W
12,2205662010_,02135,R1,454200,1910,R,N,2218.0,R,N,W
13,2205660000_,02135,R1,432200,1920,R,Y,1612.0,R,N,W
14,2205659000_,02135,R2,875200,1912,R,N,5770.0,R,N,W
15,2205658000_,02135,R1,425200,1920,R,Y,1562.0,R,N,W
16,2205657000_,02135,R1,417500,1932,R,Y,1707.0,R,N,W
17,2205656000_,02135,R1,520900,1920,R,Y,1912.0,R,N,W
18,2205655000_,02135,R2,595200,1960,R,N,2444.0,R,C,W
19,2205654000_,02135,R2,575100,1950,R,Y,2444.0,R,C,W
20,2205653000_,02135,R2,595700,1950,R,N,2716.0,R,N,W
21,2205652010_,02135,R2,640400,1965,R,N,2760.0,R,C,F
22,2205652009_,02135,R2,627900,1965,R,Y,2760.0,R,C,F
23,2205652008_,02135,R2,630900,1965,R,N,2760.0,R,C,F
24,2205652007_,02135,R2,639800,1965,R,Y,2760.0,R,C,F

In [240]:
for i in range(len(dflist)):
    print(dflist[i].LU.unique())
# see how many levels of the Type of property column in each data set
    dflist[i]["Year"] = str(i+2014)

['R3' 'CD' 'R2' 'R1' 'E' 'A' 'EA' '13' '102' '357']
['R3' 'R2' 'CD' 'R1' 'E' 'A' 'EA' 'XX']
['R1' 'R2' 'R3' 'CD' 'E' 'A' 'EA' 'XX' 'CC']
['R3' 'R2' 'CD' 'R1' 'E' 'RC' 'A' 'CC' 'EA']
['R3' 'R2' 'R1' 'CD' 'E' 'RC' 'A' 'C' 'CC' 'EA']

In [241]:
import copy
finaldata = copy.deepcopy(dflist[0])
finaldata = finaldata.append([dflist[1], dflist[2], dflist[3], dflist[4]])
finaldata.shape

(616939, 12)

In [242]:
finaldata.loc[finaldata["HEAT_TYP"] == 'w', "HEAT_TYP"] = "W"
finaldata.loc[finaldata["HEAT_TYP"] == ' F', "HEAT_TYP"] = "F"
finaldata.loc[finaldata["HEAT_TYP"] == 'f', "HEAT_TYP"] = "F"
finaldata.HEAT_TYP.unique()
# misrecoding adjustification

array(['W', 'F', 'N', 'E', 'S', 'P', 'O', 'D', 'Y', 'C', nan, ' ', 'I', 'G'], dtype=object)

In [243]:
# delete rows where HEAT_TYP equal 'D', 'Y', 'C', 'N/A', ' ', 'I','G'
finaldata = finaldata.drop(finaldata[finaldata["HEAT_TYP"].isin(['D', 'Y', 'C', ' ', 'I','G'])].index)
finaldata = finaldata.dropna(subset=["HEAT_TYP"]) 
print(finaldata.shape)
finaldata.head(20)

(616036, 12)

,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year
2,2205668000_,02135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014
5,2205665004_,02135,CD,335400,1920.0,NaN,N,1401.0,U,N,W,2014
6,2205665002_,02135,CD,357300,1920.0,NaN,N,1410.0,U,N,W,2014
8,2205664000_,02135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014
9,2205663001_,02135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014
10,2205663000_,02135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014
11,2205662020_,02135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014
12,2205662010_,02135,R1,454200,1910.0,R,N,2218.0,R,N,W,2014
13,2205660000_,02135,R1,432200,1920.0,R,Y,1612.0,R,N,W,2014
14,2205659000_,02135,R2,875200,1912.0,R,N,5770.0,R,N,W,2014
15,2205658000_,02135,R1,425200,1920.0,R,Y,1562.0,R,N,W,2014
16,2205657000_,02135,R1,417500,1932.0,R,Y,1707.0,R,N,W,2014
17,2205656000_,02135,R1,520900,1920.0,R,Y,1912.0,R,N,W,2014
18,2205655000_,02135,R2,595200,1960.0,R,N,2444.0,R,C,W,2014
19,2205654000_,02135,R2,575100,1950.0,R,Y,2444.0,R,C,W,2014
20,2205653000_,02135,R2,595700,1950.0,R,N,2716.0,R,N,W,2014
21,2205652010_,02135,R2,640400,1965.0,R,N,2760.0,R,C,F,2014
22,2205652009_,02135,R2,627900,1965.0,R,Y,2760.0,R,C,F,2014
23,2205652008_,02135,R2,630900,1965.0,R,N,2760.0,R,C,F,2014
24,2205652007_,02135,R2,639800,1965.0,R,Y,2760.0,R,C,F,2014

In [244]:
print(finaldata.HEAT_TYP.unique())

# delete 'XX' 'CC' 'C' in LU column CC and C commercial XX, and 102 don't exist in key misrecording
finaldata = finaldata.drop(finaldata[finaldata["LU"].isin(['XX', 'CC', 'C', '102'])].index)
print(finaldata.shape)
print(finaldata.LU.unique())

['W' 'F' 'N' 'E' 'S' 'P' 'O']
(616000, 12)
['R3' 'CD' 'R2' 'R1' 'E' 'A' 'EA' 'RC']

In [245]:
finaldata.head(20)

finaldata.YR_BUILT = pd.to_numeric(finaldata.YR_BUILT, errors = 'coerce')
finaldata.Year = pd.to_numeric(finaldata.Year, errors = 'coerce')
finaldata.LIVING_AREA = pd.to_numeric(finaldata.LIVING_AREA, errors = 'coerce')
print(finaldata.dtypes)

PID                 object
ZIPCODE             object
LU                  object
AV_TOTAL             int64
YR_BUILT           float64
STRUCTURE_CLASS     object
OWN_OCC             object
LIVING_AREA        float64
RorU                object
AC                  object
HEAT_TYP            object
Year                 int64
dtype: object

In [246]:
#drop all na in every column
finaldata = finaldata.dropna()
finaldata.shape

(316347, 12)

In [247]:
finaldata.head(20)

#s = pd.Series(['1', '2', '4.7', 'pandas', '10'])
#tmp = pd.to_numeric(finaldata.ZIPCODE, errors='ignore')
finaldata.ZIPCODE.unique()
#str(finaldata.loc[5]["ZIPCODE"])

array(['02135', '02134', '02467', '02215', '02445', '02446', '02132',
       '02131', '02130', '02136', '02126', '02124', '02125', '02122',
       '02121', '02119', '02118', '02115', '02199', '02120', '02116',
       '02127', '02210', '02108', '02114', '02111', '02109', '02113',
       '02129', '02128', '02186'], dtype=object)

In [270]:
#preprocessing finish 
import csv
finaldata.to_csv("Final_cleaned_up_data.csv")

In [300]:
finaldata.head(20)

,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year
2,2205668000_,02135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014
8,2205664000_,02135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014
9,2205663001_,02135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014
10,2205663000_,02135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014
11,2205662020_,02135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014
12,2205662010_,02135,R1,454200,1910.0,R,N,2218.0,R,N,W,2014
13,2205660000_,02135,R1,432200,1920.0,R,Y,1612.0,R,N,W,2014
14,2205659000_,02135,R2,875200,1912.0,R,N,5770.0,R,N,W,2014
15,2205658000_,02135,R1,425200,1920.0,R,Y,1562.0,R,N,W,2014
16,2205657000_,02135,R1,417500,1932.0,R,Y,1707.0,R,N,W,2014
17,2205656000_,02135,R1,520900,1920.0,R,Y,1912.0,R,N,W,2014
18,2205655000_,02135,R2,595200,1960.0,R,N,2444.0,R,C,W,2014
19,2205654000_,02135,R2,575100,1950.0,R,Y,2444.0,R,C,W,2014
20,2205653000_,02135,R2,595700,1950.0,R,N,2716.0,R,N,W,2014
21,2205652010_,02135,R2,640400,1965.0,R,N,2760.0,R,C,F,2014
22,2205652009_,02135,R2,627900,1965.0,R,Y,2760.0,R,C,F,2014
23,2205652008_,02135,R2,630900,1965.0,R,N,2760.0,R,C,F,2014
24,2205652007_,02135,R2,639800,1965.0,R,Y,2760.0,R,C,F,2014
25,2205652005_,02135,R2,675900,1965.0,R,Y,2760.0,R,C,F,2014
27,2205652002_,02135,R2,626100,1965.0,R,N,2760.0,R,C,N,2014

In [308]:
# Assesed value total 
# Zipcode
# HEAT_TYP
# for each zipcode, calculate the mean of all assessed value in AV_TOTAL group by zipcode
visual = copy.deepcopy(finaldata)
visual["AV_TOTALPerArea"] = visual["AV_TOTAL"]/visual["LIVING_AREA"]

visual = visual.join(visual.groupby('ZIPCODE')['AV_TOTALPerArea'].mean(), on='ZIPCODE', rsuffix='_PerZip')
#a.merge(b, left_on='ZIPCODE', right_on='ZIPCODE', how='outer')
visual.head(20)
#b.head(20)

,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year,AV_TOTALPerArea,AV_TOTALPerArea_PerZip
2,2205668000_,02135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014,213.373324,274.45179
8,2205664000_,02135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014,192.073171,274.45179
9,2205663001_,02135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014,199.832636,274.45179
10,2205663000_,02135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014,188.623775,274.45179
11,2205662020_,02135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014,215.717092,274.45179
12,2205662010_,02135,R1,454200,1910.0,R,N,2218.0,R,N,W,2014,204.779080,274.45179
13,2205660000_,02135,R1,432200,1920.0,R,Y,1612.0,R,N,W,2014,268.114144,274.45179
14,2205659000_,02135,R2,875200,1912.0,R,N,5770.0,R,N,W,2014,151.681109,274.45179
15,2205658000_,02135,R1,425200,1920.0,R,Y,1562.0,R,N,W,2014,272.215109,274.45179
16,2205657000_,02135,R1,417500,1932.0,R,Y,1707.0,R,N,W,2014,244.581136,274.45179
17,2205656000_,02135,R1,520900,1920.0,R,Y,1912.0,R,N,W,2014,272.437238,274.45179
18,2205655000_,02135,R2,595200,1960.0,R,N,2444.0,R,C,W,2014,243.535188,274.45179
19,2205654000_,02135,R2,575100,1950.0,R,Y,2444.0,R,C,W,2014,235.310966,274.45179
20,2205653000_,02135,R2,595700,1950.0,R,N,2716.0,R,N,W,2014,219.329897,274.45179
21,2205652010_,02135,R2,640400,1965.0,R,N,2760.0,R,C,F,2014,232.028986,274.45179
22,2205652009_,02135,R2,627900,1965.0,R,Y,2760.0,R,C,F,2014,227.500000,274.45179
23,2205652008_,02135,R2,630900,1965.0,R,N,2760.0,R,C,F,2014,228.586957,274.45179
24,2205652007_,02135,R2,639800,1965.0,R,Y,2760.0,R,C,F,2014,231.811594,274.45179
25,2205652005_,02135,R2,675900,1965.0,R,Y,2760.0,R,C,F,2014,244.891304,274.45179
27,2205652002_,02135,R2,626100,1965.0,R,N,2760.0,R,C,N,2014,226.847826,274.45179

In [310]:
visual.shape

(316333, 14)

In [311]:
visual.to_csv("Data_visualization.csv")

In [307]:
a = copy.deepcopy(finaldata)
#calculate AV_TOTAL_PerArea = average total/living area
a["AV_TOTALPerArea"] = a["AV_TOTAL"]/a["LIVING_AREA"]
b = pd.DataFrame(a.groupby(['ZIPCODE'])["AV_TOTALPerArea"].mean().astype(int))
#calculate average total per square feet
#group by zipcode, calculate mean of AV_TOTALPerArea for same zipcode
a = a.join(a.groupby('ZIPCODE')['AV_TOTALPerArea'].mean(), on='ZIPCODE', rsuffix='_PerZip')
#a.merge(b, left_on='ZIPCODE', right_on='ZIPCODE', how='outer')
a.head(20)
#b.head(20)

,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year,AV_TOTALPerArea,AV_TOTALPerArea_PerZip
2,2205668000_,02135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014,213.373324,274.45179
8,2205664000_,02135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014,192.073171,274.45179
9,2205663001_,02135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014,199.832636,274.45179
10,2205663000_,02135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014,188.623775,274.45179
11,2205662020_,02135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014,215.717092,274.45179
12,2205662010_,02135,R1,454200,1910.0,R,N,2218.0,R,N,W,2014,204.779080,274.45179
13,2205660000_,02135,R1,432200,1920.0,R,Y,1612.0,R,N,W,2014,268.114144,274.45179
14,2205659000_,02135,R2,875200,1912.0,R,N,5770.0,R,N,W,2014,151.681109,274.45179
15,2205658000_,02135,R1,425200,1920.0,R,Y,1562.0,R,N,W,2014,272.215109,274.45179
16,2205657000_,02135,R1,417500,1932.0,R,Y,1707.0,R,N,W,2014,244.581136,274.45179
17,2205656000_,02135,R1,520900,1920.0,R,Y,1912.0,R,N,W,2014,272.437238,274.45179
18,2205655000_,02135,R2,595200,1960.0,R,N,2444.0,R,C,W,2014,243.535188,274.45179
19,2205654000_,02135,R2,575100,1950.0,R,Y,2444.0,R,C,W,2014,235.310966,274.45179
20,2205653000_,02135,R2,595700,1950.0,R,N,2716.0,R,N,W,2014,219.329897,274.45179
21,2205652010_,02135,R2,640400,1965.0,R,N,2760.0,R,C,F,2014,232.028986,274.45179
22,2205652009_,02135,R2,627900,1965.0,R,Y,2760.0,R,C,F,2014,227.500000,274.45179
23,2205652008_,02135,R2,630900,1965.0,R,N,2760.0,R,C,F,2014,228.586957,274.45179
24,2205652007_,02135,R2,639800,1965.0,R,Y,2760.0,R,C,F,2014,231.811594,274.45179
25,2205652005_,02135,R2,675900,1965.0,R,Y,2760.0,R,C,F,2014,244.891304,274.45179
27,2205652002_,02135,R2,626100,1965.0,R,N,2760.0,R,C,N,2014,226.847826,274.45179

In [29]:
# load permit dataset
pd.set_option('display.precision',9)
permit = pd.read_csv("buildingpermits.csv", encoding = "ISO-8859-1")

permit.head(10)

,PermitNumber,WORKTYPE,PermitTypeDescr,DESCRIPTION,Comments,APPLICANT,DECLARED_VALUATION,TOTAL_FEES,ISSUED_DATE,EXPIRATION_DATE,...,OWNER,OCCUPANCYTYPE,sq_feet,ADDRESS,CITY,STATE,ZIP,Property_ID,Parcel_ID,Location
0,A100071,COB,Amendment to a Long Form,City of Boston,Change connector link layout from attached enc...,Renee Santeusanio,40000.0,429.0,2011-11-04 11:04:58,2012-05-04 00:00:00,...,CITY OF BOSTON,Comm,170.0,175 W Boundary RD,West Roxbury,MA,02132,17268.0,2012032000.0,"(42.260750000, -71.149610000)"
1,A100137,EXTREN,Amendment to a Long Form,Renovations - Exterior,Landscaping/stonework - amending permit #2801/...,NaN,15000.0,206.0,2013-01-03 14:13:09,2013-07-03 00:00:00,...,MIARA SIMON,1-2FAM,0.0,14 William Jackson AV,Brighton,MA,02135,149852.0,2204944000.0,"(42.344600000, -71.154050000)"
2,A100764,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Interior and exterior work as indicated on dra...,Gregory Pomeroy,750000.0,7565.0,2012-01-05 10:57:44,2012-07-05 00:00:00,...,CARSON DAVID THOMAS TS,1-2FAM,3663.0,81 Chestnut ST,Boston,MA,02108,31492.0,502363000.0,"(42.356838000, -71.071231000)"
3,A100858,EXTDEM,Amendment to a Long Form,Demolition - Exterior,Landmark letter and permit submittal on existi...,Arthur Choo,0.0,20.0,2012-08-21 12:27:59,2013-02-21 00:00:00,...,SDS HOSPITALITY LLC,Comm,0.0,81 S Huntington AV,Jamaica Plain,MA,02199,76833.0,1001624000.0,"(42.329910000, -71.111540000)"
4,A101019,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Amendment to add bathroom bedroom 3rd floor,JOHN MAHONY,4000.0,75.0,2011-11-25 11:20:47,2012-05-25 00:00:00,...,TROTMAN GERALD A,1-2FAM,1950.0,2 Clarkson ST,Dorchester,MA,02125,33505.0,1502933000.0,"(42.309550000, -71.065430000)"
5,A101208,EXTREN,Amendment to a Long Form,Renovations - Exterior,Amending alt77244/2011 - changes being made to...,Mike Zaisser,600.0,32.0,2011-10-21 15:49:49,2012-04-21 00:00:00,...,SMYTHE ALICE P,1-2FAM,0.0,21-23 Lee ST,Jamaica Plain,MA,02130,84830.0,1103034004.0,"(42.307200000, -71.111910000)"
6,A101379,INTREN,Amendment to a Long Form,Renovations -Interior NSC,Amend Long Form Permit 10-0840 As Follows: Mod...,Stephen Weinig,200000.0,2092.0,2012-07-11 13:29:18,2013-01-11 00:00:00,...,DYER DENNIS,Mixed,0.0,244 Newbury ST,Boston,MA,02116,101456.0,503161000.0,"(42.349410000, -71.082400000)"
7,A101551,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Finishing basement;as part of the first floor ...,Christine McMahon,50000.0,562.0,2012-04-26 18:06:35,2012-10-26 00:00:00,...,ONE-08 N STREET CONDOMINIUM,1-2FAM,680.0,108 N ST,South Boston,MA,02127,100043.0,604252000.0,"(42.334520000, -71.031083000)"
8,A101691,COB,Amendment to a Long Form,City of Boston,New Trash Compactor and Lift,Paul Hardiman Jr.,63444.0,669.0,2011-11-15 12:01:55,2012-05-15 00:00:00,...,BOSTON REDEVELOPMNT AUTH,Multi,0.0,1990 Columbus AV,Roxbury,MA,02119,35523.0,1101630000.0,"(42.315320000, -71.097200000)"
9,A101698,OTHER,Amendment to a Long Form,Other,application to amend existing permit # ALT 767...,Garland Building Company,0.0,20.0,2011-11-30 13:36:54,2012-05-30 00:00:00,...,99 SUMMER OWNER LLC,Comm,1500.0,99 Summer St,Boston,MA,02110,132058.0,304576000.0,"(42.353490000, -71.058660000)"

In [30]:
#only select rows with issued date start from 2014-2018
#permit['ISSUED_DATE'] = pd.to_datetime(permit['ISSUED_DATE'])
permit.head(10)

tmp = permit[(permit['ISSUED_DATE'] > '2012-01-01 00:00:00') & (permit['ISSUED_DATE'] < '2018-12-31 24:00:00')]

In [31]:
print("permit before:", len(permit), "permit %in% 2012 ~ 2018", len(tmp))

permit before: 363844 permit %in% 2012 ~ 2018 289372

In [33]:
train14 = train14.rename(columns = {"Parcel_ID": 'PID'}, inplace = True)
frames = [train14, train15, train16, train17, train18]
propall = pd.concat(frames)
propall.head(5)

,PID,ZIPCODE,R_HEAT_TYP,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,R_AC,U_AC,U_HEAT_TYP
0,1302299000_,02125_,W,R3,579400,1900.0,R,N,NaN,NaN
1,1302298000_,02125_,W,R2,503700,1925.0,R,N,NaN,NaN
2,1302297000_,02125_,W,R2,445800,1925.0,R,N,NaN,NaN
3,1302296000_,02125_,W,R2,434000,1930.0,R,N,NaN,NaN
4,1302295000_,02125_,W,R2,409500,1920.0,R,N,NaN,NaN

In [17]:
# change train(property assessment) data to add a new column specify whether residential

import copy

tmp = copy.deepcopy(train14)

tmp["ResidentialOrnot"] = ""
tmp.head(10)
tmp.loc[tmp['LU'].isin(["A", "R1", "R2", "R3", "R4", "RL", "CD"]), 'ResidentialOrnot'] = 'Residential'
tmp.loc[tmp['LU'].isin(["C", "CC", "CL", "CM"]), 'ResidentialOrnot'] = 'Commercial'
tmp.loc[tmp['LU'].isin(["RC"]), 'ResidentialOrnot'] = 'Mixed'
tmp.ResidentialOrnot.unique()

array(['Residential', '', 'Commercial'], dtype=object)

In [ ]:
#add up a column

for i in range(0,len(tmp)): 
    if tmp.iloc[4]["LU"] in ["A", "R1", "R2", "R3", "R4", "RL", "CD"]:
        tmp.iloc[4]["ResidentialOrnot"] = "Residential"
    elif tmp.iloc[4]["LU"] in ["C", "CC", "CL", "CM"]:
        tmp.iloc[4]["ResidentialOrnot"] = "Commercial"
    elif tmp.iloc[4]["LU"] in ["RC"]:
        tmp.iloc[4]["ResidentialOrnot"] = "Mixed"
tmp.head(15)


#tmp['LU'].isin(["A", "R1", "R2", "R3", "R4", "RL", "CD"])

In [ ]:
# import cell
import pandas as pd
import numpy as np

data14 = pd.read_csv("property-assessment-fy2014.csv")

data14hp = data14[data14.R_HEAT_TYP == "P"]
#data14nonhp = data14["R_HEAT_TYP" != "P"]

In [14]:
#only select PID, LAtitude and longitude
data16bjoin = data16[["PID", "LATITUDE", "LONGITUDE"]]

In [19]:
data16bjoin.head(20)

            PID   LATITUDE  LONGITUDE
0   1102128015_        NaN        NaN
1   1702569001_        NaN        NaN
2   1800079000_  42.272123 -71.077953
3   1801014000_  42.268792 -71.092651
4   1802070000_  42.270165 -71.103090
5   1803008000_  42.276071 -71.097266
6   1803094000_  42.277845 -71.097407
7   1807345001_        NaN        NaN
8   1000247003_  42.335426 -71.108149
9   1000366000_  42.327691 -71.098235
10  1001491100_  42.329839 -71.109986
11  1001728000_  42.324936 -71.109502
12  1001716000_  42.325066 -71.109158
13  1101679000_  42.314483 -71.094145
14  1101784000_  42.317996 -71.091663
15  1808798000_  42.257291 -71.118839
16  1809270000_  42.251993 -71.123135
17  1811991000_  42.251127 -71.134513
18  1812269056_  42.250479 -71.141135
19  1812603000_  42.244391 -71.134988

In [12]:
data16.columns

Index(['PID', 'CM_ID', 'GIS_ID', 'ST_NUM', 'ST_NAME', 'ST_NAME_SUF',
       'UNIT_NUM', 'ZIPCODE', 'PTYPE', 'LU', 'OWN_OCC', 'OWNER',
       'MAIL_ADDRESSEE', 'MAIL_ADDRESS', 'MAIL CS', 'MAIL_ZIPCODE', 'AV_LAND',
       'AV_BLDG', 'AV_TOTAL', 'GROSS_TAX', 'LAND_SF', 'YR_BUILT', 'YR_REMOD',
       'GROSS_AREA', 'LIVING_AREA', 'NUM_FLOORS', 'STRUCTURE_CLASS',
       'R_BLDG_STYL', 'R_ROOF_TYP', 'R_EXT_FIN', 'R_TOTAL_RMS', 'R_BDRMS',
       'R_FULL_BTH', 'R_HALF_BTH', 'R_BTH_STYLE', 'R_BTH_STYLE2',
       'R_BTH_STYLE3', 'R_KITCH', 'R_KITCH_STYLE', 'R_KITCH_STYLE2',
       'R_KITCH_STYLE3', 'R_HEAT_TYP', 'R_AC', 'R_FPLACE', 'R_EXT_CND',
       'R_OVRALL_CND', 'R_INT_CND', 'R_INT_FIN', 'R_VIEW', 'S_NUM_BLDG',
       'S_BLDG_STYL', 'S_UNIT_RES', 'S_UNIT_COM', 'S_UNIT_RC', 'S_EXT_FIN',
       'S_EXT_CND', 'U_BASE_FLOOR', 'U_NUM_PARK', 'U_CORNER', 'U_ORIENT',
       'U_TOT_RMS', 'U_BDRMS', 'U_FULL_BTH', 'U_HALF_BTH', 'U_BTH_STYLE',
       'U_BTH_STYLE2', 'U_BTH_STYLE3', 'U_KITCH_TYPE', 'U_KITCH_STYLE',
       'U_HEAT_TYP', 'U_AC', 'U_FPLACE', 'U_INT_FIN', 'U_INT_CND', 'U_VIEW',
       'LATITUDE', 'LONGITUDE'],
      dtype='object')

In [16]:
data = pd.read_csv("Data_Visualization.csv")

C:\Users\cindy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [18]:
data.head(20)

,Unnamed: 0,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year,AV_TOTALPerArea,AV_TOTALPerArea_PerZip
0,2,2205668000_,2135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014,213.373324,274.45179
1,8,2205664000_,2135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014,192.073171,274.45179
2,9,2205663001_,2135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014,199.832636,274.45179
3,10,2205663000_,2135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014,188.623775,274.45179
4,11,2205662020_,2135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014,215.717092,274.45179
5,12,2205662010_,2135,R1,454200,1910.0,R,N,2218.0,R,N,W,2014,204.779080,274.45179
6,13,2205660000_,2135,R1,432200,1920.0,R,Y,1612.0,R,N,W,2014,268.114144,274.45179
7,14,2205659000_,2135,R2,875200,1912.0,R,N,5770.0,R,N,W,2014,151.681109,274.45179
8,15,2205658000_,2135,R1,425200,1920.0,R,Y,1562.0,R,N,W,2014,272.215109,274.45179
9,16,2205657000_,2135,R1,417500,1932.0,R,Y,1707.0,R,N,W,2014,244.581136,274.45179
10,17,2205656000_,2135,R1,520900,1920.0,R,Y,1912.0,R,N,W,2014,272.437238,274.45179
11,18,2205655000_,2135,R2,595200,1960.0,R,N,2444.0,R,C,W,2014,243.535188,274.45179
12,19,2205654000_,2135,R2,575100,1950.0,R,Y,2444.0,R,C,W,2014,235.310966,274.45179
13,20,2205653000_,2135,R2,595700,1950.0,R,N,2716.0,R,N,W,2014,219.329897,274.45179
14,21,2205652010_,2135,R2,640400,1965.0,R,N,2760.0,R,C,F,2014,232.028986,274.45179
15,22,2205652009_,2135,R2,627900,1965.0,R,Y,2760.0,R,C,F,2014,227.500000,274.45179
16,23,2205652008_,2135,R2,630900,1965.0,R,N,2760.0,R,C,F,2014,228.586957,274.45179
17,24,2205652007_,2135,R2,639800,1965.0,R,Y,2760.0,R,C,F,2014,231.811594,274.45179
18,25,2205652005_,2135,R2,675900,1965.0,R,Y,2760.0,R,C,F,2014,244.891304,274.45179
19,27,2205652002_,2135,R2,626100,1965.0,R,N,2760.0,R,C,N,2014,226.847826,274.45179

In [20]:
#join by parcel data 2016 to get the the longitude and latitude
result = pd.merge(data, data16bjoin, on='PID')
result.head(20)

,Unnamed: 0,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year,AV_TOTALPerArea,AV_TOTALPerArea_PerZip,LATITUDE,LONGITUDE
0,2,2205668000_,2135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014,213.373324,274.45179,42.340526,-71.166393
1,87879,2205668000_,2135,R3,698100,1920.0,R,N,2834.0,R,N,W,2015,246.330275,274.45179,42.340526,-71.166393
2,95393,2205668000_,2135,R3,828400,1920.0,R,N,2834.0,R,N,W,2016,292.307692,274.45179,42.340526,-71.166393
3,170905,2205668000_,2135,R3,927800,1920.0,R,N,2834.0,R,N,W,2017,327.381793,274.45179,42.340526,-71.166393
4,8,2205664000_,2135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014,192.073171,274.45179,42.340938,-71.166342
5,87885,2205664000_,2135,R2,665800,1920.0,R,Y,2952.0,R,N,F,2015,225.542005,274.45179,42.340938,-71.166342
6,95387,2205664000_,2135,R2,797900,1920.0,R,Y,2952.0,R,N,F,2016,270.291328,274.45179,42.340938,-71.166342
7,170899,2205664000_,2135,R2,893700,1920.0,R,Y,2952.0,R,N,F,2017,302.743902,274.45179,42.340938,-71.166342
8,9,2205663001_,2135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014,199.832636,274.45179,42.341068,-71.166316
9,87886,2205663001_,2135,R1,541300,1920.0,R,Y,2390.0,R,N,W,2015,226.485356,274.45179,42.341068,-71.166316
10,95386,2205663001_,2135,R1,613300,1920.0,R,Y,2390.0,R,N,W,2016,256.610879,274.45179,42.341068,-71.166316
11,170898,2205663001_,2135,R1,650100,1920.0,R,Y,2390.0,R,N,W,2017,272.008368,274.45179,42.341068,-71.166316
12,10,2205663000_,2135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014,188.623775,274.45179,42.341174,-71.166318
13,87887,2205663000_,2135,R1,501700,1920.0,R,Y,2347.0,R,N,W,2015,213.762250,274.45179,42.341174,-71.166318
14,95385,2205663000_,2135,R1,587500,1920.0,R,Y,2347.0,R,N,W,2016,250.319557,274.45179,42.341174,-71.166318
15,170897,2205663000_,2135,R1,622700,1920.0,R,Y,2347.0,R,N,W,2017,265.317427,274.45179,42.341174,-71.166318
16,11,2205662020_,2135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014,215.717092,274.45179,42.341273,-71.166312
17,87888,2205662020_,2135,R2,633700,1910.0,R,Y,2545.0,R,N,W,2015,248.998035,274.45179,42.341273,-71.166312
18,95384,2205662020_,2135,R2,758700,1910.0,R,Y,2545.0,R,N,W,2016,298.113949,274.45179,42.341273,-71.166312
19,170896,2205662020_,2135,R2,849800,1910.0,R,Y,2545.0,R,N,W,2017,333.909627,274.45179,42.341273,-71.166312

In [22]:
result

,Unnamed: 0,PID,ZIPCODE,LU,AV_TOTAL,YR_BUILT,STRUCTURE_CLASS,OWN_OCC,LIVING_AREA,RorU,AC,HEAT_TYP,Year,AV_TOTALPerArea,AV_TOTALPerArea_PerZip,LATITUDE,LONGITUDE
0,2,2205668000_,2135,R3,604700,1920.0,R,N,2834.0,R,N,W,2014,213.373324,274.451790,42.340526,-71.166393
1,87879,2205668000_,2135,R3,698100,1920.0,R,N,2834.0,R,N,W,2015,246.330275,274.451790,42.340526,-71.166393
2,95393,2205668000_,2135,R3,828400,1920.0,R,N,2834.0,R,N,W,2016,292.307692,274.451790,42.340526,-71.166393
3,170905,2205668000_,2135,R3,927800,1920.0,R,N,2834.0,R,N,W,2017,327.381793,274.451790,42.340526,-71.166393
4,8,2205664000_,2135,R2,567000,1920.0,R,Y,2952.0,R,N,F,2014,192.073171,274.451790,42.340938,-71.166342
5,87885,2205664000_,2135,R2,665800,1920.0,R,Y,2952.0,R,N,F,2015,225.542005,274.451790,42.340938,-71.166342
6,95387,2205664000_,2135,R2,797900,1920.0,R,Y,2952.0,R,N,F,2016,270.291328,274.451790,42.340938,-71.166342
7,170899,2205664000_,2135,R2,893700,1920.0,R,Y,2952.0,R,N,F,2017,302.743902,274.451790,42.340938,-71.166342
8,9,2205663001_,2135,R1,477600,1920.0,R,Y,2390.0,R,N,W,2014,199.832636,274.451790,42.341068,-71.166316
9,87886,2205663001_,2135,R1,541300,1920.0,R,Y,2390.0,R,N,W,2015,226.485356,274.451790,42.341068,-71.166316
10,95386,2205663001_,2135,R1,613300,1920.0,R,Y,2390.0,R,N,W,2016,256.610879,274.451790,42.341068,-71.166316
11,170898,2205663001_,2135,R1,650100,1920.0,R,Y,2390.0,R,N,W,2017,272.008368,274.451790,42.341068,-71.166316
12,10,2205663000_,2135,R1,442700,1920.0,R,Y,2347.0,R,N,W,2014,188.623775,274.451790,42.341174,-71.166318
13,87887,2205663000_,2135,R1,501700,1920.0,R,Y,2347.0,R,N,W,2015,213.762250,274.451790,42.341174,-71.166318
14,95385,2205663000_,2135,R1,587500,1920.0,R,Y,2347.0,R,N,W,2016,250.319557,274.451790,42.341174,-71.166318
15,170897,2205663000_,2135,R1,622700,1920.0,R,Y,2347.0,R,N,W,2017,265.317427,274.451790,42.341174,-71.166318
16,11,2205662020_,2135,R2,549000,1910.0,R,Y,2545.0,R,N,W,2014,215.717092,274.451790,42.341273,-71.166312
17,87888,2205662020_,2135,R2,633700,1910.0,R,Y,2545.0,R,N,W,2015,248.998035,274.451790,42.341273,-71.166312
18,95384,2205662020_,2135,R2,758700,1910.0,R,Y,2545.0,R,N,W,2016,298.113949,274.451790,42.341273,-71.166312
19,170896,2205662020_,2135,R2,849800,1910.0,R,Y,2545.0,R,N,W,2017,333.909627,274.451790,42.341273,-71.166312
20,12,2205662010_,2135,R1,454200,1910.0,R,N,2218.0,R,N,W,2014,204.779080,274.451790,42.341393,-71.166304
21,87889,2205662010_,2135,R1,514800,1910.0,R,N,2218.0,R,N,W,2015,232.100992,274.451790,42.341393,-71.166304
22,95383,2205662010_,2135,R1,593300,1910.0,R,N,2218.0,R,N,W,2016,267.493237,274.451790,42.341393,-71.166304
23,170895,2205662010_,2135,R1,628900,1910.0,R,N,2218.0,R,N,W,2017,283.543733,274.451790,42.341393,-71.166304
24,13,2205660000_,2135,R1,432200,1920.0,R,Y,1612.0,R,N,W,2014,268.114144,274.451790,42.341548,-71.166276
25,87890,2205660000_,2135,R1,489800,1920.0,R,Y,1612.0,R,N,W,2015,303.846154,274.451790,42.341548,-71.166276
26,95382,2205660000_,2135,R1,558200,1920.0,R,Y,1612.0,R,N,W,2016,346.277916,274.451790,42.341548,-71.166276
27,170894,2205660000_,2135,R1,591600,1920.0,R,Y,1612.0,R,N,W,2017,366.997519,274.451790,42.341548,-71.166276
28,14,2205659000_,2135,R2,875200,1912.0,R,N,5770.0,R,N,W,2014,151.681109,274.451790,42.341770,-71.166274
29,87891,2205659000_,2135,R2,1033900,1912.0,R,N,5770.0,R,N,W,2015,179.185442,274.451790,42.341770,-71.166274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254740,84420,1200046100_,2119,R3,446700,1900.0,R,N,3168.0,R,N,W,2017,141.003788,140.960061,42.327614,-71.082497
254741,84500,1200122000_,2119,R3,488530,1890.0,R,N,3900.0,R,C,F,2017,125.264103,140.960061,42.324864,-71.080192
254742,85910,1202018000_,2121,R3,444600,1900.0,R,N,2970.0,R,N,W,2017,149.696970,113.419477,42.314591,-71.087496
254743,86026,1202139000_,2121,R2,1120840,1910.0,D,N,5886.0,R,C,F,2017,190.424737,113.419477,42.312707,-71.085353
254744,86468,1202516000_,2121,R3,530500,1935.0,R,N,4674.0,R,N,W,2017,113.500214,113.419477,42.309234,-71.084002
254745,86922,1202953000_,2121,R2,370000,1900.0,R,N,2983.0,R,N,W,2017,124.036205,113.419477,42.315421,-71.079965
254746,87324,1203333000_,2121,R3,435300,1905.0,R,N,4176.0,R,N,W,2017,104.238506,113.419477,42.316874,-71.090492
254747,88332,1300865000_,2121,R3,501400,1905.0,R,N,3768.0,R,N,F,2017,133.067941,113.419477,42.313677,-71.076369
254748,90823,1302646000_,2125,R3,570100,1910.0,R,Y,3255.0,R,N,F,2017,175.145929,152.744213,42.314859,-71.052375
254749,91274,1302965000_,2125,R3,715900,1905.0,R,N,3900.0,R,N,F,2017,183.564103,152.744213,42.316535,-71.055529
254750,92410,1400355001_,2121,R3,247200,1935.0,C,Y,4248.0,R,N,W,2017,58.192090,113.419477,42.309085,-71.074397
254751,94491,1402334000_,2121,R3,550400,1910.0,R,N,3620.0,R,N,F,2017,152.044199,113.419477,42.297377,-71.078349
254752,95719,1403475000_,2124,R3,468900,1905.0,R,N,3258.0,R,N,F,2017,143.922652,156.665060,42.283667,-71.088622
254753,98485,1500713000_,2124,R3,436400,1910.0,R,N,3320.0,R,N,F,2017,131.445783,156.665060,42.300418,-71.068217
254754,102732,1601039000_,2122,R3,535700,1900.0,R,N,3585.0,R,N,F,2017,149.428173,170.648268,42.295006,-71.058256
254755,107918,1604898000_,2124,R2,519000,1930.0,D,N,2844.0,R,N,W,2017,182.489451,156.665060,42.281105,-71.065199
254756,112055,1703178000_,2124,R2,494000,1920.0,R,Y,3004.0,R,N,W,2017,164.447403,156.665060,42.278987,-71.073883
254757,113626,1704310000_,2124,R3,767800,1992.0,D,N,1152.0,R,N,F,2017,666.493056,156.665060,42.282563,-71.068592
254758,113626,1704310000_,2124,R3,767800,1992.0,D,N,1152.0,R,N,F,2017,666.493056,156.665060,42.282563,-71.068592
254759,113627,1704310000_,2124,R3,767800,1905.0,D,N,4635.0,R,N,F,2017,165.652643,156.665060,42.282563,-71.068592
254760,113627,1704310000_,2124,R3,767800,1905.0,D,N,4635.0,R,N,F,2017,165.652643,156.665060,42.282563,-71.068592
254761,113883,1704537000_,2124,R3,527800,1905.0,R,N,3264.0,R,N,F,2017,161.703431,156.665060,42.283989,-71.065823
254762,130183,1812962000_,2136,R1,279800,1899.0,C,N,4794.0,R,N,W,2017,58.364622,200.762432,42.238576,-71.137817
254763,133177,1901516001_,2130,R2,568500,1910.0,D,N,2484.0,R,N,W,2017,228.864734,280.475967,42.308533,-71.115798
254764,136509,1903702000_,2131,R2,477200,1910.0,R,N,2680.0,R,C,W,2017,178.059701,224.678591,42.285269,-71.121412
254765,145543,2005559000_,2131,R2,837936,1920.0,D,N,4628.0,R,C,F,2017,181.057908,224.678591,42.287620,-71.136971
254766,146589,2006471000_,2132,R1,298600,2015.0,D,N,2360.0,R,C,F,2017,126.525424,265.868249,42.291467,-71.157872
254767,156127,2101005000_,2134,R2,737820,1930.0,C,Y,2220.0,R,C,F,2017,332.351351,255.940038,42.349446,-71.135177
254768,156637,2101217000_,2134,R2,693100,1910.0,D,N,2981.0,R,N,F,2017,232.505871,255.940038,42.351681,-71.141895
254769,163177,2102847000_,2135,R2,845900,1900.0,R,Y,3138.0,R,N,W,2017,269.566603,274.451790,42.345122,-71.152456

In [25]:
result.to_csv("Data_Visualization_LON_LAT.csv")